### ISSUE TITLE
Add Community Health Files

### ISSUE THREAD

**Issue by soumyadeepkun** [sdk2k01/Gestures_I3D#5]
Add default community health files for the project in a `.github` directory in the project's root, as per [reference.](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)

For starters, we can have two subdirectories under the `.github` directory as `.github/ISSUE_TEMPLATE` (containing templates for different types of issues, as the name suggests) and `.github/docs` (containing templates for pull requests, etc.).

**Comment by soumyadeepkun** [comment]
@Roopshali can you take this up in the meantime?

**Comment by Roopshali** [comment]
@sdk2k01 yes sure
